"""
Constants and Enums for the 9 HR Capability Agents in Microsoft AI Foundry.
Adheres strictly to the KPMG Agent Factory Framework (Stages 1-7A).
"""
from enum import Enum

class AgentID(str, Enum):
    A01_WORKSPACE = "A01_WORKSPACE"
    A02_ORCHESTRATOR = "A02_ORCHESTRATOR"
    A03_DATA_MANAGEMENT = "A03_DATA_MANAGEMENT"
    A04_EXCEPTION_PROCESSING = "A04_EXCEPTION_PROCESSING"
    A05_ANALYSIS = "A05_ANALYSIS"
    A06_DECISION_INTELLIGENCE = "A06_DECISION_INTELLIGENCE"
    A07_QUALITY_CONTROL = "A07_QUALITY_CONTROL"
    A08_GOVERNANCE_AUDIT = "A08_GOVERNANCE_AUDIT"
    A09_HUMAN_APPROVAL = "A09_HUMAN_APPROVAL"

class AnomalyClass(str, Enum):
    LEAVER_STILL_PAID = "leaver_still_paid"
    JOINER_NOT_PAID = "joiner_not_paid"
    UNEXPLAINED_VARIANCE = "unexplained_variance"
    MISSING_TAX_CODE = "missing_tax_code"
    NEGATIVE_NET_PAY = "negative_net_pay"
    DUPLICATE_PAY_RECORD = "duplicate_pay_record"
    UNAPPROVED_PAY_CHANGE = "unapproved_pay_change"

class Severity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class WorkflowStep(str, Enum):
    W01_COLLECT_DATA = "W01"
    W02_VALIDATE_INPUT = "W02"
    W03_DETECT_ANOMALIES = "W03"
    W04_CALCULATE_RISK = "W04"
    W05_CLASSIFY_ANOMALY = "W05"
    W06_EXPLAIN_CALCULATION = "W06"
    W07_DETERMINE_ROOT_CAUSE = "W07"
    W08_LOCATE_SOR = "W08"
    W09_GENERATE_OPTIONS = "W09"
    W10_ASSESS_IMPACT = "W10"
    W11_CREATE_RECOMMENDATION = "W11"
    W12_ESCALATE_APPROVAL = "W12"
    W13_REVIEW_RECOMMENDATION = "W13"
    W14_HUMAN_DECISION = "W14"
    W15_COMMIT_CORRECTION = "W15"
    W16_RECALCULATE_PAYROLL = "W16"
    W17_VALIDATE_OUTCOME = "W17"
    W18_CREATE_AUDIT_EVIDENCE = "W18"
    W19_LOG_GOVERNANCE = "W19"
    W20_CLOSE_CASE = "W20"

class CaseState(str, Enum):
    INITIATED = "INITIATED"
    INGESTED = "INGESTED"
    INPUT_VALIDATED = "INPUT_VALIDATED"
    ANOMALIES_DETECTED = "ANOMALIES_DETECTED"
    ANALYZED = "ANALYZED"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    COMMITTED = "COMMITTED"
    RECALCULATED = "RECALCULATED"
    POST_VALIDATED = "POST_VALIDATED"
    EVIDENCE_ASSEMBLED = "EVIDENCE_ASSEMBLED"
    CLOSED = "CLOSED"
    HELD_FOR_REVIEW = "HELD_FOR_REVIEW"

class ApprovalAction(str, Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    ESCALATE = "ESCALATE"
    OVERRIDE = "OVERRIDE"
